### ISSUE TITLE
Can I get an API SDK for dotnet core?

### ISSUE THREAD

**Issue by matthewcv** [Moraware/APISamples#1]
Or do you have a schema for your XML that I can use to generate my own SDK?

**Comment by patrickfoley** [comment]
Hi Matthew,

We don't have a schema for the XML - the existing API should work just fine in dotnet core - if not, can you write me at patrick@moraware.com and let me know what trouble you're having?

**Comment by matthewcv** [comment]
I downloaded it and noticed that it was a .net framework 4.5 assembly and dumbly assumed that it wouldn't work in .net core. I can add it as a reference to my project and it does work. Thanks for the response, though. I will let you know if I have other problems.
